# Schema for the configuration files of the Asu data potluck module.
asu_data_potluck.settings:
  type: config_object
  label: 'Asu data potluck settings'
  mapping:
    example:
      type: string
      label: 'Example'
