asu_degree_rfi:
  rfi_source_id: fake-for-testing
  rfi_submission_handler_url: 'https://5gu33wnsdm2mpgmob4c2rt3mbq0mngfo.lambda-url.us-west-2.on.aws/'
  rfi_degree_search_datasource_endpoint: ''
  rfi_asuonline_datasource_endpoint: ''
  rfi_country_province_datasource_endpoint: ''
  program_list_datasource_endpoint: ''
  program_list_datasource_method: ''
  program_list_datasource_init: ''
  program_detail_datasource_endpoint: ''
  program_detail_datasource_method: ''
  program_detail_datasource_init: ''
