_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  allowed_formats: 0
  anchor_link: 0
  asu_brand: 0
  asu_components_appearance: 0
  asu_events: 0
  asu_footer: 0
  asu_news: 0
  asu_react_core: 0
  asu_react_integration: 0
  asu_user: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  cas: 0
  ckeditor: 0
  ckeditor_responsive_plugin: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_readonly: 0
  config_update: 0
  contact: 0
  contextual: 0
  crop: 0
  current_page_crumb: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  decorative_image_widget: 0
  dynamic_page_cache: 0
  editor: 0
  editoria11y: 0
  entity_reference_revisions: 0
  fakeobjects: 0
  field: 0
  field_group: 0
  field_menu: 0
  field_states_ui: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_form_errors: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  layout_section_classes: 0
  link: 0
  linkit: 0
  maxlength: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  robotstxt: 0
  schema_metatag: 0
  search: 0
  seckit: 0
  select2: 0
  shortcut: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  webspark_blocks: 0
  webspark_cas: 0
  webspark_ckeditor_plugins: 0
  webspark_cropper_theme: 0
  webspark_installer_forms: 0
  webspark_module_asu_breadcrumb: 0
  webspark_module_renovation_layouts: 0
  webspark_module_views_pager: 0
  webspark_utility: 0
  webspark_webdir: 0
  pathauto: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  webspark: 1000
theme:
  bartik: 0
  seven: 0
  radix: 0
  renovation: 0
profile: webspark
