_core:
  default_config_hash: IQjf_ytthngZTAk_MU8-74VecArWD3G5g0oEH6PM6GA
toolbar_items:
  - devel.cache_clear
  - devel.configs_list
  - devel.container_info.service
  - devel.route_info.item
  - devel.admin_settings_link
  - devel.entity_info_page
  - devel.field_info_page
  - devel.layout_info
  - devel.menu_rebuild
  - devel.reinstall
  - devel.route_info
  - devel.run_cron
  - devel.session
