name: 'Site Builder Role'
description: 'Creates the Site Builder role.'
type: Site
config:
  actions:
    user.role.site_builder:
        createIfNotExists:
          id: site_builder
          label: 'Site Builder'
          weight: 3
          is_admin: false
          permissions:
            - 'access user profiles'
            - 'administer account settings'
            - 'administer permissions'
            - 'administer users'
            - 'view user email addresses'
            - 'access administration pages'
            - 'access block library'
            - 'access content'
            - 'access content overview'
            - 'access contextual links'
            - 'access files overview'
            - 'access help pages'
            - 'access shortcuts'
            - 'access site in maintenance mode'
            - 'access site reports'
            - 'access site-wide contact form'
            - 'access taxonomy overview'
            - 'access toolbar'
            - 'administer block content'
            - 'administer block types'
            - 'administer block_content display'
            - 'administer block_content fields'
            - 'administer block_content form display'
            - 'administer blocks'
            - 'administer contact forms'
            - 'administer contact_message display'
            - 'administer contact_message fields'
            - 'administer contact_message form display'
            - 'administer content types'
            - 'administer display modes'
            - 'administer image styles'
            - 'administer menu'
            - 'administer node display'
            - 'administer node fields'
            - 'administer node form display'
            - 'administer nodes'
            - 'administer search'
            - 'administer shortcuts'
            - 'administer site configuration'
            - 'administer taxonomy'
            - 'administer taxonomy_term display'
            - 'administer taxonomy_term fields'
            - 'administer taxonomy_term form display'
            - 'administer url aliases'
            - 'administer views'
            - 'bypass node access'
            - 'create article content'
            - 'create page content'
            - 'create url aliases'
            - 'customize shortcut links'
            - 'delete all revisions'
            - 'delete all taxonomy revisions'
            - 'delete any article content'
            - 'delete any file'
            - 'delete any page content'
            - 'delete article revisions'
            - 'delete page revisions'
            - 'edit any article content'
            - 'edit any page content'
            - 'link to any page'
            - 'revert all revisions'
            - 'revert all taxonomy revisions'
            - 'revert article revisions'
            - 'revert page revisions'
            - 'use advanced search'
            - 'use text format basic_html'
            - 'use text format full_html'
            - 'view all revisions'
            - 'view all taxonomy revisions'
            - 'view article revisions'
            - 'view own unpublished content'
            - 'view page revisions'
            - 'view the administration theme'
            - 'view vocabulary labels'
