webspark_webdir.settings:
  type: config_object
  label: 'WebSpark WebDir Settings'
  mapping:
    api:
      type: string
      label: 'API Base URL'
    api_version:
      type: string
      label: 'API Version Path'
    departments:
      type: string
      label: 'Departments Endpoint'
    people_departments:
      type: string
      label: 'People Departments Endpoint'
    people_search:
      type: string
      label: 'People Search Endpoint'
    people_data:
      type: string
      label: 'People Data Endpoint'
    people_department:
      type: string
      label: 'People Department Endpoint'
    profile_affiliations:
      type: string
      label: 'Profile Affiliations Endpoint'
    employee_types:
      type: string
      label: 'Employee Types Endpoint'
    expertise_areas:
      type: string
      label: 'Expertise Areas Endpoint'
    filtered_people_department:
      type: string
      label: 'Filtered People Department Endpoint'
