name: 'Split ASU Packages'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  packages_split:
    if: github.repository == 'ASUWebPlatforms/webspark-release-stable'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          - local_path: 'asu_brand'
            split_repository: 'asu_brand_fork'
          - local_path: 'asu_user'
            split_repository: 'asu_user_fork'

    steps:
      -   uses: "actions/checkout@v4.1.7"

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          # ↓ split "/web/modules/asu_modules/*" directory
          package_directory: 'web/modules/asu_modules/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/asuwebplatforms/* repository
          repository_organization: 'ASUWebPlatforms'
          repository_name: '${{ matrix.package.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: "tbutterf"
          user_email: "tbutterf@asu.edu"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "/web/modules/asu_modules/*" directory
          package_directory: 'web/modules/asu_modules/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/asuwebplatforms/* repository
          repository_organization: 'ASUWebPlatforms'
          repository_name: '${{ matrix.package.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: "tbutterf"
          user_email: "tbutterf@asu.edu"
